import { sql } from 'drizzle-orm';
import { integer, timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Standard columns shared by every table. Always call these helpers (never share builder
 * instances between tables) and spread the result into the table definition:
 *
 *   export const rooms = pgTable('rooms', { ...baseColumns(), name: text().notNull() });
 */

/** Time-ordered UUIDv7 primary key, generated by PostgreSQL 18. */
export const idColumn = () =>
  uuid('id')
    .primaryKey()
    .default(sql`uuidv7()`);

export const timestampColumns = () => ({
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdateFn(() => new Date()),
});

/** Who created / last changed the row (user account id). Null for system writes. */
export const auditColumns = () => ({
  createdBy: uuid('created_by'),
  updatedBy: uuid('updated_by'),
});

/** Optimistic locking: every update must match and increment this (see `updateWithVersion`). */
export const versionColumn = () => ({
  version: integer('version').notNull().default(1),
});

/** Soft delete, only for tables where hiding a record is a UX need. Never for financial rows. */
export const softDeleteColumn = () => ({
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
});

export const baseColumns = () => ({
  id: idColumn(),
  ...timestampColumns(),
  ...auditColumns(),
  ...versionColumn(),
});
